# Generated by Django 2.2.5 on 2020-01-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolioPic',
            new_name='profilePic',
        ),
    ]
